use_frameworks!

platform :ios, '8.0'

target 'PYBaseEventHandler_Example' do
  pod 'PYBaseEventHandler', :path => '../'

  target 'PYBaseEventHandler_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
